# Generated by Django 4.2.5 on 2023-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSPU_Library_Website', '0002_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_status',
            name='table_id',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
