# Generated by Django 4.2.5 on 2023-11-29 14:52

import LSPU_Library_Website.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LSPU_Library_Website', '0003_table_status_table_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateField(default=django.utils.timezone.now)),
                ('student_full_name', models.CharField(default='invalid', max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('student_college', models.CharField(max_length=50)),
                ('student_course', models.CharField(max_length=50)),
                ('purpose_of_entry', models.CharField(max_length=200)),
                ('time_of_entry', models.TimeField(default=LSPU_Library_Website.models.get_current_time)),
                ('time_of_out', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
