# Generated by Django 4.2.5 on 2023-11-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSPU_Library_Website', '0004_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='student_college',
            new_name='student_department',
        ),
    ]
