# Generated by Django 4.2.5 on 2023-12-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSPU_Library_Website', '0005_rename_student_college_history_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_status',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
