# Generated by Django 4.2.5 on 2023-12-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSPU_Library_Website', '0006_alter_table_status_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_status',
        ),
    ]
